{{HTML::style("css/bootstrap.css")}}
{{HTML::style("css/bootstrap-responsive.css")}}
{{HTML::style("css/bootmetro.css")}}
{{HTML::style("css/bootmetro-tiles.css")}}
{{HTML::style("css/bootmetro-charms.css")}}
{{HTML::style("css/metro-ui-semilight.css")}}
{{HTML::style("css/jqClock.css")}}
{{HTML::style("css/icomoon.css")}}
{{HTML::style("css/demo.css")}}
{{HTML::style("scripts/google-code-prettify/prettify.css")}}
{{HTML::style("css/image_upload.css")}}
{{HTML::style("css/clock.css")}}